
version: '3.6'
services:

  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888

  zoo2:
    image: zookeeper
    restart: always
    hostname: zoo2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888

  kafka1:
    image: wurstmeister/kafka
    ports:
      - "9093:9092"
    environment:
       #   KAFKA_ADVERTISED_HOST_NAME  #deprecated
      HOSTNAME_COMMAND: "docker info | grep ^' Node Address:'| cut -d' ' -f 4"
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2182
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9093
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LOG_DIRS: /kafka/kafka-logs
      KAFKA_BROKER_ID: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/mozat/logs/kafka-logs/broker1:/kafka/kafka-logs
    depends_on:
      - zoo1
      - zoo2

  kafka2:
    image: wurstmeister/kafka
    ports:
      - "9094:9092"
    environment:
   #   KAFKA_ADVERTISED_HOST_NAME  #deprecated
      HOSTNAME_COMMAND: "docker info | grep ^' Node Address:'| cut -d' ' -f 4"
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2182
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LOG_DIRS: /kafka/kafka-logs
      KAFKA_BROKER_ID: 2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/mozat/logs/kafka-logs/broker2:/kafka/kafka-logs
    depends_on:
      - zoo1
      - zoo2


